version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - todo-app-network

  nginx:
    image: nginx:alpine
    container_name: todo-app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - todo-app-network

  db:
    image: mysql:8.0
    container_name: todo_app_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo_app_db
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3306:3306"
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge
